# Generated by Django 5.1.2 on 2025-09-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_book_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('ビジネス', 'ビジネス'), ('生活', '生活'), ('エロ', 'エロ'), ('その他', 'その他')], max_length=100),
        ),
    ]
