# Generated by Django 5.1.2 on 2025-09-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='auther',
            field=models.CharField(default='不明', max_length=100),
            preserve_default=False,
        ),
    ]
