# Generated by Django 5.1.2 on 2025-09-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_book_auther'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='auther',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
