# Generated by Django 5.1.2 on 2025-09-07 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_book_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='auther',
            new_name='author',
        ),
    ]
